# Generated by Django 4.2 on 2026-02-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='accounts_cu_phone_n_908ea4_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='accounts_cu_telegra_5542ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginhistory',
            name='accounts_lo_user_id_088230_idx',
        ),
        migrations.RemoveIndex(
            model_name='loginhistory',
            name='accounts_lo_ip_addr_142937_idx',
        ),
        migrations.RemoveIndex(
            model_name='otp',
            name='accounts_ot_user_id_3058e7_idx',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='attempts',
        ),
        migrations.RemoveField(
            model_name='otp',
            name='max_attempts',
        ),
    ]
